image: docker:20.10.16

services:
  - name: docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""       # отключает TLS, упрощает настройку
  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
stages:
  - build

build:
  stage: build
  script:
    - docker info               # проверка Docker-окружения
    - mvn clean install         # запуск сборки и тестов

