image: docker:20.10.16  # образ, в котором запускаются команды

services:
  - name: docker:dind  # Docker-in-Docker, чтобы запускать контейнеры из pipeline
    command: ["--tls=false"]  # отключаем tls для простоты

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""  # отключение TLS
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2"
  TC_CLOUD_TOKEN: ""  # если используешь Testcontainers Cloud

stages:
  - build

build:
  stage: build
  script:
    - docker info  # проверяем, что Docker доступен
    - mvn clean install -DskipTests  # собираем проект, пропуская тесты для запуска pipeline; позже можно включить тесты

